const express = require("express");
const authMiddleware = require("../middlewares/auth.middleware");
const {
  validateBody,
  validateParams,
  validateQuery,
} = require("../middlewares/validate.middleware");
const {
  createEventSchema,
  updateEventSchema,
  listEventsQuerySchema,
  listFeaturedEventsQuerySchema,
  listMyEventsQuerySchema,
  eventIdParamsSchema,
  organizerIdParamsSchema,
  ticketIdParamsSchema,
  postIdParamsSchema,
  ticketBidParamsSchema,
  ticketTodoParamsSchema,
  initializeTicketPurchaseSchema,
  initializeResalePurchaseSchema,
  verifyTicketPaymentSchema,
  ticketCheckInSchema,
  listMyTicketsQuerySchema,
  listOrganizerTicketSalesQuerySchema,
  listEventRatingsQuerySchema,
  rateEventSchema,
  listEventFeedQuerySchema,
  eventReminderSchema,
  eventChatMessageBodySchema,
  eventChatMessageParamsSchema,
  updateEventChatMessageBodySchema,
  eventChatQuerySchema,
  createEventPostSchema,
  listEventPostsQuerySchema,
  createEventPostCommentSchema,
  listEventPostCommentsQuerySchema,
  createTicketResaleSchema,
  listTicketResaleBidsQuerySchema,
  createTicketResaleBidSchema,
  listEventResaleMarketplaceQuerySchema,
  createTicketTodoSchema,
  updateTicketTodoSchema,
} = require("../validations/event.validation");
const {
  createEventController,
  listEventsController,
  listFeaturedEventsController,
  listMyEventsController,
  getEventController,
  getOrganizerProfileController,
  listEventRatingsController,
  rateEventController,
  updateEventController,
  deleteEventController,
  initializeTicketPurchaseController,
  verifyTicketPaymentController,
  checkInTicketController,
  listMyTicketsController,
  listOrganizerTicketSalesController,
  getTicketController,
  listEventTicketsController,
  listEventResaleMarketplaceController,
  createTicketResaleController,
  cancelTicketResaleController,
  listTicketResaleBidsController,
  createTicketResaleBidController,
  acceptTicketResaleBidController,
  rejectTicketResaleBidController,
  purchaseResaleTicketController,
  initializeResalePurchaseController,
  verifyResalePurchaseController,
  listTicketTodosController,
  createTicketTodoController,
  updateTicketTodoController,
  deleteTicketTodoController,
  listEventFeedController,
  getEventReminderController,
  updateEventReminderController,
  listEventChatController,
  createEventChatMessageController,
  updateEventChatMessageController,
  deleteEventChatMessageController,
  listEventPostsController,
  createEventPostController,
  toggleEventPostLikeController,
  listEventPostCommentsController,
  createEventPostCommentController,
} = require("../controllers/event.controller");

const router = express.Router();

router.use(authMiddleware);

router.get("/", validateQuery(listEventsQuerySchema), listEventsController);
router.get("/feed", validateQuery(listEventFeedQuerySchema), listEventFeedController);
router.get(
  "/featured",
  validateQuery(listFeaturedEventsQuerySchema),
  listFeaturedEventsController,
);
router.get(
  "/organizers/:organizerId",
  validateParams(organizerIdParamsSchema),
  getOrganizerProfileController,
);
router.get("/mine", validateQuery(listMyEventsQuerySchema), listMyEventsController);
router.post("/", validateBody(createEventSchema), createEventController);

router.get(
  "/tickets/me",
  validateQuery(listMyTicketsQuerySchema),
  listMyTicketsController,
);
router.get(
  "/tickets/sales",
  validateQuery(listOrganizerTicketSalesQuerySchema),
  listOrganizerTicketSalesController,
);
router.post(
  "/tickets/check-in",
  validateBody(ticketCheckInSchema),
  checkInTicketController,
);
router.get(
  "/tickets/:ticketId",
  validateParams(ticketIdParamsSchema),
  getTicketController,
);
router.post(
  "/tickets/:ticketId/verify",
  validateParams(ticketIdParamsSchema),
  validateBody(verifyTicketPaymentSchema),
  verifyTicketPaymentController,
);
router.post(
  "/tickets/:ticketId/resale",
  validateParams(ticketIdParamsSchema),
  validateBody(createTicketResaleSchema),
  createTicketResaleController,
);
router.delete(
  "/tickets/:ticketId/resale",
  validateParams(ticketIdParamsSchema),
  cancelTicketResaleController,
);
router.get(
  "/tickets/:ticketId/resale-bids",
  validateParams(ticketIdParamsSchema),
  validateQuery(listTicketResaleBidsQuerySchema),
  listTicketResaleBidsController,
);
router.post(
  "/tickets/:ticketId/resale-bids",
  validateParams(ticketIdParamsSchema),
  validateBody(createTicketResaleBidSchema),
  createTicketResaleBidController,
);
router.post(
  "/tickets/:ticketId/resale-bids/:bidId/accept",
  validateParams(ticketBidParamsSchema),
  acceptTicketResaleBidController,
);
router.post(
  "/tickets/:ticketId/resale-bids/:bidId/reject",
  validateParams(ticketBidParamsSchema),
  rejectTicketResaleBidController,
);
router.post(
  "/tickets/:ticketId/resale-purchase/initialize",
  validateParams(ticketIdParamsSchema),
  validateBody(initializeResalePurchaseSchema),
  initializeResalePurchaseController,
);
router.post(
  "/tickets/:ticketId/resale-purchase/verify",
  validateParams(ticketIdParamsSchema),
  validateBody(verifyTicketPaymentSchema),
  verifyResalePurchaseController,
);
router.post(
  "/tickets/:ticketId/resale-purchase",
  validateParams(ticketIdParamsSchema),
  purchaseResaleTicketController,
);
router.get(
  "/tickets/:ticketId/todos",
  validateParams(ticketIdParamsSchema),
  listTicketTodosController,
);
router.post(
  "/tickets/:ticketId/todos",
  validateParams(ticketIdParamsSchema),
  validateBody(createTicketTodoSchema),
  createTicketTodoController,
);
router.patch(
  "/tickets/:ticketId/todos/:todoId",
  validateParams(ticketTodoParamsSchema),
  validateBody(updateTicketTodoSchema),
  updateTicketTodoController,
);
router.delete(
  "/tickets/:ticketId/todos/:todoId",
  validateParams(ticketTodoParamsSchema),
  deleteTicketTodoController,
);

router.get(
  "/:eventId/ratings",
  validateParams(eventIdParamsSchema),
  validateQuery(listEventRatingsQuerySchema),
  listEventRatingsController,
);
router.get(
  "/:eventId/resale-marketplace",
  validateParams(eventIdParamsSchema),
  validateQuery(listEventResaleMarketplaceQuerySchema),
  listEventResaleMarketplaceController,
);
router.post(
  "/:eventId/ratings",
  validateParams(eventIdParamsSchema),
  validateBody(rateEventSchema),
  rateEventController,
);
router.get(
  "/:eventId/reminders/me",
  validateParams(eventIdParamsSchema),
  getEventReminderController,
);
router.post(
  "/:eventId/reminders/me",
  validateParams(eventIdParamsSchema),
  validateBody(eventReminderSchema),
  updateEventReminderController,
);
router.get(
  "/:eventId/chat",
  validateParams(eventIdParamsSchema),
  validateQuery(eventChatQuerySchema),
  listEventChatController,
);
router.post(
  "/:eventId/chat",
  validateParams(eventIdParamsSchema),
  validateBody(eventChatMessageBodySchema),
  createEventChatMessageController,
);
router.patch(
  "/:eventId/chat/:messageId",
  validateParams(eventChatMessageParamsSchema),
  validateBody(updateEventChatMessageBodySchema),
  updateEventChatMessageController,
);
router.delete(
  "/:eventId/chat/:messageId",
  validateParams(eventChatMessageParamsSchema),
  deleteEventChatMessageController,
);
router.get(
  "/:eventId/posts",
  validateParams(eventIdParamsSchema),
  validateQuery(listEventPostsQuerySchema),
  listEventPostsController,
);
router.post(
  "/:eventId/posts",
  validateParams(eventIdParamsSchema),
  validateBody(createEventPostSchema),
  createEventPostController,
);
router.post(
  "/posts/:postId/likes/toggle",
  validateParams(postIdParamsSchema),
  toggleEventPostLikeController,
);
router.get(
  "/posts/:postId/comments",
  validateParams(postIdParamsSchema),
  validateQuery(listEventPostCommentsQuerySchema),
  listEventPostCommentsController,
);
router.post(
  "/posts/:postId/comments",
  validateParams(postIdParamsSchema),
  validateBody(createEventPostCommentSchema),
  createEventPostCommentController,
);

router.get("/:eventId", validateParams(eventIdParamsSchema), getEventController);
router.patch(
  "/:eventId",
  validateParams(eventIdParamsSchema),
  validateBody(updateEventSchema),
  updateEventController,
);
router.delete(
  "/:eventId",
  validateParams(eventIdParamsSchema),
  deleteEventController,
);
router.post(
  "/:eventId/tickets/initialize",
  validateParams(eventIdParamsSchema),
  validateBody(initializeTicketPurchaseSchema),
  initializeTicketPurchaseController,
);
router.get(
  "/:eventId/tickets",
  validateParams(eventIdParamsSchema),
  validateQuery(listMyTicketsQuerySchema),
  listEventTicketsController,
);

module.exports = router;
